version: '3.8'
services:
  database:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_DB: plasmid_database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432